# ===================================================================
#TODO Add desciption for the application 
#
# 
# 
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

management:
    context-path: /management
    health:
        mail:
            enabled: false # When using the MailService, configure an SMTP server and set this to true
spring:
    application:
        name: employee-service
    profiles:
        # The commented value for `active` can be replaced with valid spring profiles to load.
        # Otherwise, it will be filled in by maven when building the WAR file
        # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: dev
    boot:
       admin:
         url: http://localhost:8080
  #  boot:
    #   admin:
     #    url: http://localhost:8080
   
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        show-sql: false
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
        hibernate: 
            ddl-auto: create-drop
   
    datasource:
        url: jdbc:h2:mem:schedulesys_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=create schema if not exists schedulesys_db;
        username: sa
        password: 
        type: com.zaxxer.hikari.HikariDataSource
        data: classpath:data/data.sql
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: XHTML    
    mail: 
       host: localhost
       
liquibase:
    contexts: dev
    
schedule-sys:
  security:
    authentication:
      jwt:
        secret: 54947df0-0e9e-4471-a2f9-9af509fb5889
  cors:
    allowed-origins:
      - http://localhost:8082
      
logging:
  level:
    org:
     springframework: 
                   jdbc: 
                      core: DEBUG



