spring:
    application:
        name: schedule-sys
    profiles:
        active: dev
   
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        show-sql: false
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
        hibernate: 
            ddl-auto: create-drop
   
    datasource:
        url: jdbc:h2:mem:schedulesys_db;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=create schema if not exists schedulesys_db;
        username: sa
        password: 
        type: com.zaxxer.hikari.HikariDataSource
        data: classpath:data/data.sql
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: XHTML    
    mail: 
       host: localhost
       
liquibase:
    contexts: dev
    
schedule-sys:
  security:
    authentication:
      jwt:
        secret: 54947df0-0e9e-4471-a2f9-9af509fb5889
  cors:
    allowed-origins:
      - http://localhost:4200
      - http://localhost:8080
      
logging:
    level:
       org:
        springframework: 
                     jdbc: 
                       core: DEBUG